/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness plus the two numbers a client needs to check compatibility.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Bookmarks
         * @description List your saves.
         *
         *     `mode=all` is the intersection the tag sidebar is built on — `python` AND `fastapi`.
         *     `untagged=true` is how you work the backlog.
         */
        get: operations["list_bookmarks_api_v1_bookmarks_get"];
        put?: never;
        /**
         * Save Bookmark
         * @description Save a page.
         *
         *     201 the first time, 200 every time after, never a second row — whatever the spelling
         *     of the URL and however many clients call at once. Tags in the payload are merged on
         *     every call, so re-saving with new tags adds them rather than failing.
         */
        post: operations["save_bookmark_api_v1_bookmarks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookmarks/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lookup Bookmark
         * @description Have I saved this page, and with what tags?
         *
         *     A read. `POST /bookmarks` is idempotent and would answer the same question, but it is
         *     a write: a client calling it merely to ask would create a bookmark every time someone
         *     opened a popup. 404 means not saved, which is a normal answer here.
         */
        get: operations["lookup_bookmark_api_v1_bookmarks_lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookmarks/{save_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bookmark */
        get: operations["get_bookmark_api_v1_bookmarks__save_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Bookmark
         * @description Unsave a page.
         *
         *     A soft delete of *your* save. The `bookmark` row and anything crawled for it survive,
         *     because they belong to everyone; and re-saving the page restores this row rather than
         *     creating a second one.
         */
        delete: operations["delete_bookmark_api_v1_bookmarks__save_id__delete"];
        options?: never;
        head?: never;
        /** Patch Bookmark */
        patch: operations["patch_bookmark_api_v1_bookmarks__save_id__patch"];
        trace?: never;
    };
    "/api/v1/bookmarks/{save_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Tags */
        post: operations["add_tags_api_v1_bookmarks__save_id__tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookmarks/{save_id}/tags/{tag_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Tag */
        delete: operations["remove_tag_api_v1_bookmarks__save_id__tags__tag_name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tags
         * @description Your tags, with how often you have used them.
         *
         *     The vocabulary is global (ADR 0002) but the counts are yours: what belongs in an
         *     autocomplete list is how often *you* reach for a tag. Ranking by usage rather than
         *     alphabetically is what makes a 567-entry vocabulary usable at all.
         */
        get: operations["list_tags_api_v1_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BookmarkCreate */
        BookmarkCreate: {
            /** Url */
            url: string;
            /**
             * Title
             * @description The page's title as the client saw it, such as the browser tab's title. Refreshed by every save that sends one. A title you choose goes through PATCH instead, and wins over this one and over the crawled title.
             */
            title?: string | null;
            /** Saved From */
            saved_from?: string | null;
            /** Tags */
            tags?: string[];
        };
        /** BookmarkOut */
        BookmarkOut: {
            /** Id */
            id: number;
            /** Url */
            url: string;
            /** Title */
            title: string | null;
            /** Site */
            site: string | null;
            /** Saved From */
            saved_from: string | null;
            /** Created At */
            created_at: string | null;
            /** Notes */
            notes?: string | null;
            /** Tags */
            tags: string[];
        };
        /** BookmarkPage */
        BookmarkPage: {
            /** Items */
            items: components["schemas"]["BookmarkOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** BookmarkPatch */
        BookmarkPatch: {
            /**
             * Title
             * @description A title you choose. It wins over the title seen at save time and the crawled one, and survives every re-save. An empty string clears it.
             */
            title?: string | null;
            /** Notes */
            notes?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description What a client needs to decide whether it can talk to this deployment.
         *
         *     `contract` is the one to check: it is the API contract version, independent of
         *     `version`, which is the release label and moves every deploy.
         */
        Health: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Database */
            database: boolean;
            /** Version */
            version: string;
            /** Contract */
            contract: number;
            /** Schema Revision */
            schema_revision?: string | null;
        };
        /** TagOut */
        TagOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Count */
            count: number;
        };
        /** TagsIn */
        TagsIn: {
            /** Tags */
            tags: string[];
            /**
             * Source
             * @default user
             * @enum {string}
             */
            source: "user" | "ai" | "rule" | "import";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_bookmarks_api_v1_bookmarks_get: {
        parameters: {
            query?: {
                /** @description Comma-separated tag names */
                tags?: string | null;
                mode?: "all" | "any";
                site?: string | null;
                /** @description Substring match on title or URL */
                q?: string | null;
                /** @description Only bookmarks with no tags */
                untagged?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_bookmark_api_v1_bookmarks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookmarkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_bookmark_api_v1_bookmarks_lookup_get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bookmark_api_v1_bookmarks__save_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                save_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_bookmark_api_v1_bookmarks__save_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                save_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_bookmark_api_v1_bookmarks__save_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                save_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookmarkPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_tags_api_v1_bookmarks__save_id__tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                save_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_tag_api_v1_bookmarks__save_id__tags__tag_name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                save_id: number;
                tag_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_v1_tags_get: {
        parameters: {
            query?: {
                /** @description Substring match on tag name */
                q?: string | null;
                min_count?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
